### ISSUE TITLE
Bug in FromByteArray while handling IO_REPARSE_TAG_AF_UNIX

### ISSUE THREAD

**Issue by nurfed1** [googleprojectzero/sandbox-attacksurface-analysis-tools#28]
I encountered the following bug in [FromByteArray](https://github.com/googleprojectzero/sandbox-attacksurface-analysis-tools/blob/7845fc068f74f77b93ed8c6d10ccf7c0f95ccaed/NtApiDotNet/ReparseBuffer.cs#L125) while executing [DumpReparsePoints](https://github.com/tyranid/DumpReparsePoints) with the handling of the IO_REPARSE_TAG_AF_UNIX tag.

filename: "C:\\Users\\xxxx\\AppData\\Local\\Packages\\TheDebianProject.DebianGNULinux_76v4gfsz19hv4\\LocalState\\fsserver" ends up with the bytestream: 230000800000000000000000000000000000000000000000

    BinaryReader reader = new BinaryReader(new MemoryStream(ba), Encoding.Unicode); // results in IO_REPARSE_TAG_AF_UNIX (0x80000023)
    ReparseTag tag = (ReparseTag)reader.ReadUInt32(); // results in IO_REPARSE_TAG_AF_UNIX (0x80000023)
    int data_length = reader.ReadUInt16(); // results in 0 
    // Reserved
    reader.ReadUInt16();  // obsolete
    long remaining_length = reader.RemainingLength(); // results in 16 (Remaining null bytes)
    long expected_length = data_length; // results in 0 
    if (!NtFileUtils.IsReparseTagMicrosoft(tag)) // returns false, doesn't enter the if statement
    {
        expected_length += 16; // obsolete
    }

    if (remaining_length != expected_length) // 16 != 0, enters the if statement
    {
        // Corrupted buffer. Return an opaque buffer with all the data until the end.
        return new OpaqueReparseBuffer(tag, reader.ReadToEnd()); // reader.ReadToEnd() ends with a System.OutOfMemoryException
    }

**Comment by tyranid** [comment]
Thanks for the report. Seems it was really a bug in ReadToEnd, how that ever worked I don't know :-) Should be fixed upstream.
