### ISSUE TITLE
Get-AccessibleFile feature

### ISSUE THREAD

**Issue by nurfed1** [googleprojectzero/sandbox-attacksurface-analysis-tools#29]
Get-AccessibleFile -Recurse currently doesn't follow symlink and junction directories and I suppose this makes sense. However, I can see some cases where it's useful to follow such directories. 

Could it be considered implementing an additional flag for this, that can be used in combination with the recurse flag?

**Comment by tyranid** [comment]
Thanks for the feature request. I'll have a look at the difficulty of it. The key is making sure it doesn't end up in an infinite loop :-)

**Comment by tyranid** [comment]
I've added support to the three path based Get-Accessible* cmdlets. You specify FollowLink with Recurse and it should follow links. If you have the ability I'd welcome any feedback..
