### ISSUE TITLE
Win32Utils: Incorrect spelling in CreateSecurityCapabilities

### ISSUE THREAD

**Issue by WildByDesign** [googleprojectzero/sandbox-attacksurface-analysis-tools#30]
James, I was just testing out some of the new features introduced with the most recent 1.1.29 release and I came across some spelling mistakes in the code. Particularly, I've got a lot of interest in _Added proper enumeration of AppContainer profiles and support creating with capabilities_. So when I was digging into that code, I came across the spelling mistakes which I believe date back further in time.

Quick search: https://github.com/googleprojectzero/sandbox-attacksurface-analysis-tools/search?q=%22CreateSecuityCapabilities%22

Incorrect: Win32Utils.CreateSecuityCapabilities
Correct: Win32Utils.CreateSecurityCapabilities

1. https://github.com/googleprojectzero/sandbox-attacksurface-analysis-tools/blob/master/NtApiDotNet/Win32/Win32ProcessConfig.cs#L449
2. https://github.com/googleprojectzero/sandbox-attacksurface-analysis-tools/blob/master/NtApiDotNet/Win32/TokenUtils.cs#L420
3. https://github.com/googleprojectzero/sandbox-attacksurface-analysis-tools/blob/master/NtApiDotNet/Win32/Win32Utils.cs#L435

I don't know if this would cause any functional issues or whether it is just a benign spelling typo in the code, but figured I should mention it to you. Cheers!

**Comment by tyranid** [comment]
Thanks, it is only an internal function so it doesn't really matter that it's spelt incorrectly but I've fixed it anyway :-)
