### ISSUE TITLE
Provide .net standard nuget packages

### ISSUE THREAD

**Issue by anhaehne** [googleprojectzero/sandbox-attacksurface-analysis-tools#31]
Hi,

is it possible you provide Nuget packages targeting .net standard?

I saw the NtApiDotNet.Core.csproj but couldn't find a corresponding nuget package.

**Comment by tyranid** [comment]
Yes, I've not released core packages as in my experience I've not had a good reason to, the build was more to support PowerShell Core which works fairly okay with just .NET framework assemblies. However, with .NET5 maybe it's time to finally do so. I've noticed alas that the current release (1.1.29) doesn't actually build, so I need to fix that but I'll sort out of a build for that version with quick tweaks and upload it as a separate NtApiDotNet.Core package.

**Comment by tyranid** [comment]
I've released a .NET standard 2.0 build of the library on NuGet. Hope that's useful.

**Comment by tyranid** [comment]
Sorry, here's a link. https://www.nuget.org/packages/NtApiDotNet.Core/
