### ISSUE TITLE
GitHub Actions?

### ISSUE THREAD

**Issue by rgl** [googleprojectzero/sandbox-attacksurface-analysis-tools#33]
Does it make sense to have a GitHub Actions Workflow  to automatically build the source and respective Release.7z artifact of this repository? If you want that, I can probably do a PR.

**Comment by tyranid** [comment]
Thanks for the offer.  TBH as I'm the primary author I don't think it really needs automated building or CI, at least at the moment. If I was to added proper testing (or really any testing) then I'd probably be interested in adding it.

**Comment by rgl** [comment]
Even without tests I find it useful to have CI making sure the build works outside of my machine. As a bonus, this also works for giving feedback to PR authors.
