### ISSUE TITLE
RTL_USER_PROCESS_PARAMETERS

### ISSUE THREAD

**Issue by arsium** [googleprojectzero/sandbox-attacksurface-analysis-tools#36]
Hello,
I was searching for RTL_USER_PROCESS_PARAMETERS in your project but can't find it. You did not implement it ?

**Comment by tyranid** [comment]
It's there, it's just calling RtlUserProcessParameters. https://github.com/googleprojectzero/sandbox-attacksurface-analysis-tools/blob/master/NtApiDotNet/NtUserProcessParameters.cs#L83 in any case you shouldn't use that (unless you need to write something), you should instead call the GetUserProcessParameters method on an NtProcess object which returns an NtUserProcessParameters structure.
