### ISSUE TITLE
Binary representation for CLAIM_SECURITY_ATTRIBUTE_V1 (resource attribute) implementation

### ISSUE THREAD

**Issue by YuryStrozhevsky** [googleprojectzero/sandbox-attacksurface-analysis-tools#38]
I propose you to implement binary encoding for CLAIM_SECURITY_ATTRIBUTE_V1 data type. It is required for making "resource attribute" in security descriptor. The binary encoding is not officially documented, but you can find an example [**here**](https://github.com/YuryStrozhevsky/XSEC/blob/main/lib/claims.h#L942).

**Comment by tyranid** [comment]
Hi thanks for the request. XSEC looks an interesting project.

I'm sure I already have this functionality in https://github.com/googleprojectzero/sandbox-attacksurface-analysis-tools/blob/master/NtApiDotNet/Utilities/Token/ClaimSecurityAttributeBuilder.cs is there something I'm missing? That does marshaling back and forth between the [CLAIM_SECURITY_ATTRIBUTE_RELATIVE_V1](https://docs.microsoft.com/en-us/windows/win32/api/winnt/ns-winnt-claim_security_attribute_relative_v1) type (which is documented if you follow that link). Conditional expressions on the other hand I still currently cheat by round tripping them through the SDDL parser. I plan at some point to parse the byte code and allow manipulation at the low level, perhaps even implement my own evaluator.

**Comment by YuryStrozhevsky** [comment]
@tyranid Thank you for the good words to my project. As for [**ClaimSecurityAttributeBuilder**](https://github.com/googleprojectzero/sandbox-attacksurface-analysis-tools/blob/master/NtApiDotNet/Utilities/Token/ClaimSecurityAttributeBuilder.cs): I have been searching your project again and can find usage of the class in scope of tokens only. No relations with security descriptor. Am I missing something?

**Comment by tyranid** [comment]
Yeah it's used by the Ace class when you set the ResourceAttribute property. https://github.com/googleprojectzero/sandbox-attacksurface-analysis-tools/blob/master/NtApiDotNet/Ace.cs#L249 it's slightly obfuscated, but basically it converts to the ClaimSecurityAttribute object to a builder and from there marshals it to a byte array.

**Comment by YuryStrozhevsky** [comment]
You are right, seems I missed details. The making from binary data for CLAIM_SECURITY_ATTRIBUTE_V1 data type is [**here**](https://github.com/googleprojectzero/sandbox-attacksurface-analysis-tools/blob/master/NtApiDotNet/ClaimSecurityAttribute.cs#L130) and making a binary data from the type is [**here**](https://github.com/googleprojectzero/sandbox-attacksurface-analysis-tools/blob/master/NtApiDotNet/Utilities/Token/ClaimSecurityAttributeBuilder.cs#L448). Sorry for disturbance.
