### ISSUE TITLE
Can Get-RpcAlpcServer retrieve information from process inside a container?

### ISSUE THREAD

**Issue by g3rzi** [googleprojectzero/sandbox-attacksurface-analysis-tools#48]
Does `Get-RpcAlpcServer` can get the RpcAlpcServer from a process inside a container?  
I had a container running with process `CExecSvc.exe` (PID 4880) but when I tried to get it with the above function it didn't find it:  
```powershell
PS C:\Windows\system32> Get-RpcAlpcServer| where {$_.ProcessName -eq "cexecsvc.exe"}
PS C:\Windows\system32> Get-RpcAlpcServer -ProcessId 4880
PS C:\Windows\system32>
```  

I noticed that RPCView also can't get this information.  
This is not critical for me because I used the workaround with `Get-RpcServer` on the file itself, just wondering if this is a bug or currently not possible.  

![image](https://user-images.githubusercontent.com/11998736/146240141-db0c5e16-b4c8-4d57-80a2-dd4caf058e22.png)

Reference:  
https://github.com/googleprojectzero/sandbox-attacksurface-analysis-tools/blob/c02ed8ba04324e54a0a188ab9877ee6aa372dfac/NtApiDotNet/Win32/RpcAlpcServer.cs#L91-L112

**Comment by tyranid** [comment]
It might work if I expand the check to find \RPC Control\ anywhere in the name. This also affects AppContainers as well so might be worth doing. You could try and do it manually by extracting the path to the ALPC Port and then using the Get-RpcEndpoint command instead. e.g.

```
$name = (Get-NtHandle -ProcessId <PID OF EXE> | ? ObjectType -eq 'ALPC Port' | ? Name -Match 'RPC Control').Name
Get-RpcEndpoint -AlpcPort $name
```

I've not tested that though.

**Comment by g3rzi** [comment]
Yes, it does the job, thank you :)

```powershell
PS C:\Users\Administrator> $name = (Get-NtHandle -ProcessId 4880 | ? ObjectType -eq 'ALPC Port' | ? Name -Match 'RPC Control').Name
PS C:\Users\Administrator> Get-RpcEndpoint -AlpcPort $name

UUID                                 Version Protocol Endpoint                        Annotation
----                                 ------- -------- --------                        ----------
75ef42c7-22f4-44a0-8200-9351cd316e01 1.0     ncalrpc  \Silos\532\RPC Control\cexecsvc
```
