### ISSUE TITLE
Does Params object contains too much parameters: "Cannot find an overload..."

### ISSUE THREAD

**Issue by g3rzi** [googleprojectzero/sandbox-attacksurface-analysis-tools#49]
Hi James, 
I was checking the function `HcsRpc_ShutdownSystem` (from `vmcompute.exe` - HCS service):  
```powershell
PS> $a = Get-RpcServer "C:\windows\system32\vmcompute.exe" -DbgHelpPath "C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\dbghelp.dll"

PS> $a.Procedures[4]

Name             : HcsRpc_ShutdownSystem
Params           : {FC_SUPPLEMENT - NdrSupplementTypeReference - IsIn, , FC_UP - NdrPointerTypeReference - MustSize, MustFree, IsIn, FC_HYPER - NdrSimpleTypeReference - IsIn,
                   IsBasetype...}
```  

l saw it has 4 arguments (there is a fifth without a `Name` so I don't know if I should include it):  
```powershell
PS> $a.Procedures[4].Params


Attributes      : IsIn
Type            : FC_SUPPLEMENT - NdrSupplementTypeReference
ServerAllocSize : 0
Offset          : 0
Name            : p0
IsIn            : True
IsOut           : False
IsInOut         : False
IsSimpleRef     : False

Explicit        : True
Generic         : False
Attributes      : 0
Type            : FC_BIND_CONTEXT - NdrSimpleTypeReference
ServerAllocSize : 0
Offset          : 0
Name            :
IsIn            : False
IsOut           : False
IsInOut         : False
IsSimpleRef     : False

Attributes      : MustSize, MustFree, IsIn
Type            : FC_UP - NdrPointerTypeReference
ServerAllocSize : 0
Offset          : 8
Name            : p1
IsIn            : True
IsOut           : False
IsInOut         : False
IsSimpleRef     : False

Attributes      : IsIn, IsBasetype
Type            : FC_HYPER - NdrSimpleTypeReference
ServerAllocSize : 0
Offset          : 16
Name            : p2
IsIn            : True
IsOut           : False
IsInOut         : False
IsSimpleRef     : False

Attributes      : MustSize, MustFree, IsOut
Type            : FC_RP - NdrPointerTypeReference
ServerAllocSize : 8
Offset          : 24
Name            : p3
IsIn            : False
IsOut           : True
IsInOut         : False
IsSimpleRef     : False
```

I connected the client:  
```powershell
PS> $a.Endpoints

UUID                                 Version Protocol Endpoint                Annotation
e7a216af-1ec1-447f-8d3f-a87278db564d 1.0     ncalrpc  LRPC-6981a149a72e0ebb3e

PS> $client = Get-RpcClient $rpc
PS> Connect-RpcClient $c -EndpointPath "LRPC-6981a149a72e0ebb3e"
PS> $c.Connected
True
```  
But when I tried to call it with 4 parameters (`p0,p1,p2 and p3`) it didn't accept it:  
```powershell
PS> $c.HcsRpc_ShutdownSystem([NullString]::Value, [NullString]::Value, [NullString]::Value, [NullString]::Value)
Cannot find an overload for "HcsRpc_ShutdownSystem" and the argument count: "4".
```

But with 3 parameters it didn't throw the "Cannot find an overload" error.  
It throw other error about using the wrong type but this is a different issue.  

I am currently want to understand why the `Params` shows me 4 (maybe 5) parameters when the client can send only 3.   

I reversed the `vmcompute.exe` and `vmcompute.dll`, it seems that in both (server and client) it receives 4 parameters and not 3:  
![image](https://user-images.githubusercontent.com/11998736/146925388-9c19da05-2f68-4f0f-85f7-690790589e8c.png)
  
Why I am getting the overload error when using 4 parameters?

**Comment by g3rzi** [comment]
I followed the example you showed in your [blog post about RPC](https://googleprojectzero.blogspot.com/2021/04/who-contains-containers.html).  
You called `RCreateServiceW` with 15 parameters:  
```powershell
PS> $service = $client.RCreateServiceW($scm.p3, "GreatEscape", "", `
 [NtApiDotNet.Win32.ServiceAccessRights]::Start, 0x10, 0x3, 0, $cmd, `
 [NullString]::Value, $null, $null, 0, [NullString]::Value, $null, 0)
```  

When I checked the function I saw that it has `p0` - `p15` (+ `FC_BIND_CONTEXT` which doesn't have a name) which are 17 parameters and you still used only 15 of them.    

```powershell
PS C:\Users\Administrator> $b[0].Procedures[12]


Name             : RCreateServiceW
Params           : {FC_BIND_CONTEXT - NdrHandleTypeReference - IsIn, , FC_RP - NdrPointerTypeReference - MustSize,
                   MustFree, IsIn, FC_UP - NdrPointerTypeReference - MustSize, MustFree, IsIn...}
ReturnValue      : FC_LONG - NdrSimpleTypeReference - IsOut, IsReturn, IsBasetype
Handle           : FC_BIND_CONTEXT - NdrSimpleTypeReference - 0
...

PS> $b[0].Procedures[12].Params.Count
17
```  

I can understand that the empty one (`FC_BIND_CONTEXT`) is something special but I still have one parameter too much.

**Comment by tyranid** [comment]
It only exposes 3 as the PowerShell client defaults to wrapping out parameters to make it easier to call. When you want to do output parameter in PS you need to create the variable then use the special [ref] type, this is just a pain. So instead for PS I create a return structure which will hold the output values and the return code and remove that parameter from the function's argument list. 

You can use the raw interfaces if you like by clearing the flags when creating the client, e.g. `Get-RpcClient $server -Flags None`.  

Also it's 4 and not 5 as I remove redundant handle parameters, my implementation doesn't need them so I don't expose them as they're not sent over the wire anyway.

Hope that makes sense.

**Comment by g3rzi** [comment]
So as rule of thumb, the "extra" parameter will usually be last set with one of the following to `True`?   
```
IsOut, IsInOut, IsSimpleRef 
```

In my case, the "extra" parameter, the one which is supposed to be with the `[ref]` type is `p3` ?  
```powershell
Attributes      : MustSize, MustFree, IsOut
Type            : FC_RP - NdrPointerTypeReference
ServerAllocSize : 8
Offset          : 24
Name            : p3
IsIn            : False
IsOut           : True
IsInOut         : False
IsSimpleRef     : False
```

I can identify it by the `IsOut` set to `True`.

**Comment by tyranid** [comment]
Yes if `IsOut` is `True` then the parameter will not be in the argument list, but instead will be in the returned structure. If `IsInOut` is `True` then the parameter will be both in the argument list for the value to send to the RPC server, and the updated value will be returned in the structure. This allows for by reference parameters to be used without having to deal with the PS `[ref]` stuff.

**Comment by g3rzi** [comment]
Great, thank you very much for your informative answers! :)
