### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by avboy1337** [googleprojectzero/sandbox-attacksurface-analysis-tools#52]
错误	CS0165	使用了未赋值的局部变量“ticket”	NtApiDotNet	D:\sandbox-attacksurface-analysis-tools\NtApiDotNet\Win32\Security\Authentication\Kerberos\Builder\KerberosTicketBuilder.cs	208	活动

**Comment by avboy1337** [comment]
when compile release version , the above error make tips

**Comment by tyranid** [comment]
Thanks for the report I should have fixed the compile issue.
