### ISSUE TITLE
Add wrappers for CreateBindLink and RemoveBindLink APIs

### ISSUE THREAD

**Issue by kobykahane** [googleprojectzero/sandbox-attacksurface-analysis-tools#77]
In Windows 11 24H2, BindFlt now has public APIs for creation and removal of bind links, as described in https://learn.microsoft.com/en-us/windows/win32/bindlink/bindlink-overview.

It would be useful for NtObjectManager to have wrappers for these APIs, since overwriting file or directory paths or introducing merges would certainly have security implications in many scenarios.

**Comment by tyranid** [comment]
Interesting APIs. I'll have to take a look. Thanks.

**Comment by tyranid** [comment]
Even though this seems to be documented I can't seem to find the DLL that it references even in Win11 insider preview with containers installed. If it appears later I'll revisit, but as NtObjectManager supports communicating with filters perhaps the low-level API can be reverse engineered and used directly.

**Comment by kobykahane** [comment]
The docs incorrectly say it is in bindlink.dll (which doesn't exist) when it is in fact in bindfltapi.dll.

**Comment by tyranid** [comment]
Ah yes, see them now. Stupid Microsoft documentation :)

**Comment by kobykahane** [comment]
For what it's worth, I was able to grab bindfltapi.dll from 24H2 and load it on 22H2 and successfully send the filter port message to the 22H2 bindflt.sys to create a merged bind link and remove it (i.e., the actual layout of the filter port message seems to have remained the same as it was before the introduction of the public API).
